---
title: "Metabolomics dgk"
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/MET_DGK/")) 
```

```{r}
library(xlsx)
library(ggfortify)
```

## Plan
1) volcano plot 5 months
2) Heatmap (all samples)
3) network


## load/parsing data
```{r}
data <- read.xlsx("/home/flomik/Desktop/Code-PHD/MET_DGK/data/Serum omics data from 5 and 12- months old dGK ko mice.xlsx",2, header = FALSE)
names <- data.frame(t(data[1,]))
names <- as.vector(names$X1)
data <- read.xlsx("/home/flomik/Desktop/Code-PHD/MET_DGK/data/Serum omics data from 5 and 12- months old dGK ko mice.xlsx",2)
colnames(data)[-c(1:5)] <- names[-c(1:5)]
```
```{r}
conversion <- read.xlsx("/home/flomik/Desktop/Code-PHD/MET_DGK/data/Serum omics data from 5 and 12- months old dGK ko mice.xlsx",3)
conversion <- conversion[,c(1:2)]
```

## check normality
```{r}
pdf("results/figures/distribution_data.pdf")
data_2 <-as.matrix(data[,c(6:96)])
hist(data_2 , prob=T)
curve(dnorm(x,mean(data_2),sd(data_2)),add=T,col="red")
dev.off()
```
```{r}
data[,c(6:96)] <- log2(data[,c(6:96)])
```

```{r}
pdf("results/figures/distribution_data_after_norm.pdf")
data_2 <-as.matrix(data[,c(6:96)])
hist(data_2 , prob=T)
curve(dnorm(x,mean(data_2),sd(data_2)),add=T,col="red")
dev.off()
```
## PCA
```{r}
pca_data <- data.frame(group = data$Condition_2, as.matrix(data[,c(6:96)]))
```

```{r}
pca_data[is.na(pca_data)] <-  0
pca <- prcomp(pca_data[,-1])
```

)+ scale_fill_manual()
```{r}
data$Condition_2 <- factor(data$Condition_2, levels = c("WT5", "KO5", "WT12", "KO12"))
```

```{r}
pdf("results/figures/pca_dgk_met.pdf")
autoplot(pca, data = pca_data, size= 6, shape = 21, fill = 'group')+theme_gray()+
  stat_ellipse(geom = "polygon", alpha = 0.1, aes(fill = data$Condition_2))+ #Size and alpha just for fun
   scale_fill_manual(values = c("#dcedc1", "#ffd3b6", "#a8e6cf", "#ffaaa5"))
dev.off()
```

```{r}
dge_5 <- read.xlsx("/home/flomik/Desktop/Code-PHD/MET_DGK/data/Metaboliomics data from 5 and 12 months dGK KO mice.xlsx",1)
dge_12 <- read.xlsx("/home/flomik/Desktop/Code-PHD/MET_DGK/data/Metaboliomics data from 5 and 12 months dGK KO mice.xlsx",2)
```
```{r}
dge_5$FDR <- p.adjust(dge_5$P.value, method = "fdr")
```

## adjust pvalues
```{r}
dge_5_pval <- dge_5[dge_5$P.value < 0.05,]
dge_5_FDR <- dge_5[dge_5$FDR < 0.1, ]
```
```{r}
top_genes <- dge_5[dge_5$P.value < 0.05,]
#top_genes <- top_genes[(top_genes$Log2.FC > 0.5) | (top_genes$Log2.FC < - 0.5), ]
top_genes <- top_genes[complete.cases(top_genes),]


dim(top_genes)
# remove label for proteins with  - 1 < logFoldChange < 1
for (nb_row in 1:nrow(dge_5)){
  if (dge_5[nb_row, 1] %in% top_genes$Genes){
    }else{
      dge_5[nb_row, 1] <- NA
  }
}
```


```{r}
tt <- dge_5

tt$color <- NA

for (i in 1:nrow(tt)){
  if(tt[i, 4] > 0.5 & tt[i, 2] < 0.05){
    tt[i, 6] <- "up_regulated"
  }
  if(tt[i, 4] < -0.5 & tt[i, 2] < 0.05){
    tt[i, 6] <- "down_regulated"
  }
  if(tt[i, 2] > 0.05){
    tt[i, 6] <- "NS"
  }
}
```
```{r}
tt$color[is.na(tt$color)] <- "significant"
```

## volcano plot ggplot

```{r}
library(ggrepel)
```
```{r}
names(tt)
```

# creating color palette
cols <- c("up_regulated" = "#cc0000", "down_regulated" = "#009933", "NS" = "darkgrey", "significant" = "#ffff99")

# Make a basic ggplot2 object

```{r}
vol <- ggplot(tt, aes(x = Log2.FC, y = -log10(P.value), color = Log2.FC))+ 
  geom_point(size=3, alpha = 3, na.rm = T)+ scale_color_gradient2(midpoint = 0, low = "#003300", mid = "#ffffcc",
                            high = "#800000", space = "Lab" )+ 
  theme(legend.title=element_text(size=15),legend.text=element_text(size=6),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
        axis.text.y=element_text(size=18),axis.text.x=element_text(size=18)) +
  labs(x="Log2 Fold Change",y="-log10 (pvalue)") +
  xlim(-2.5, 2.5)+
  geom_text_repel(aes(label = Genes),size=3,label.size = 0.1, color = "black")

vol
path_fig <- paste0("results/volcano_plot_5_months.pdf")
ggsave(path_fig)
```

## heatmap
```{r}
data_pval <- data[, colnames(data) %in% dge_5_pval$Genes]
names_sing <- colnames(data_pval)
rownames(data_pval) <- data$NA.
```
```{r}
data_pval <- data.frame(scale(data_pval))
names(data_pval) <- names_sing
```


             
             
             row_split = input$Pathway,
             
             
             
             

```{r}
data$Condition_2 <- factor(data$Condition_2, levels = c("WT5", "KO5", "WT12", "KO12"))
```
   
```{r}
max(data_pval)
```
         
```{r}
library(circlize)
library(ComplexHeatmap)

col_fun1 = colorRamp2(c(-4,-1.25,-0.5, 0, 0.5,1.25,4), c("#7F7F00","#B2B200" ,"#E5E500","white","#BF7FBF","#993299","#590059"))

col_fun = colorRamp2(c(-2, 0, 2), c("green", "white", "red"))


pdf("results/Heatmat_dgk_met_significant.pdf", height = 6, width = 10)


Heatmap(t(data_pval),
             col = col_fun1,
             column_order = rownames(data_pval),
             show_column_names = FALSE,
             column_split = data$Condition_2, row_title_rot = 0,
             column_gap = unit(1, "mm"),
             column_title_gp = gpar(fill = c("#dcedc1", "#ffd3b6", "#a8e6cf", "#ffaaa5")), border = TRUE)


dev.off()
```
```{r}
list_met <- colnames(data_pval)
```
```{r}
ids <- conversion[conversion$Metabolite %in% list_met,]
```
```{r}
write.csv(ids, "processing/significant_hmdb.csv")
```
```{r}
data[,c(6:96)] <- data.frame(scale(data[,c(6:96)]))
```

```{r}
rownames(data) <- data$NA.
```

```{r}
library(circlize)
library(ComplexHeatmap)

col_fun1 = colorRamp2(c(-2,-1,-0.5, 0,0.5,1,2), c("#7F7F00","#B2B200" ,"#E5E500","white","#BF7FBF","#993299","#590059"))

col_fun = colorRamp2(c(-2, 0, 2), c("green", "white", "red"))


pdf("results/Heatmat_dgk_met.pdf", width = 18, height = 10)


ht = Heatmap(as.matrix(data[,c(6:96)]),
             col = col_fun1,
             show_row_names = TRUE)

ht_list = ht

draw(ht_list)
dev.off()
```
